[package]
name = "plane-noisy"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = "0.11.4"
#serde = "1.0.130"
tokio = { version = "1.11.0", features = ["full"] }
#serde_json = "1.0.68"
scraper = "0.12.0"
chrono = "0.4.19"